### PR TITLE
Fix relaydocker

### LINKED ISSUE #162: relaydock | truffle: command not found
steps to reproduce:
1. Clone repo, `cd tabookey-gasless` and `yarn`
2. `./dock/run.sh` to build the relaydock docker image.
3. `./dock/run.sh yarn`  to install dependency. 
4. `./dock/run.sh ./restart-relay.sh `

**logs below:**

```
echo "Using GOPATH=/home/nervehammer/Desktop/push/tabookey-gasless/server:/home/nervehammer/Desktop/push/tabookey-gasless/server/../build/server"
Using GOPATH=/home/nervehammer/Desktop/push/tabookey-gasless/server:/home/nervehammer/Desktop/push/tabookey-gasless/server/../build/server
mkdir -p /home/nervehammer/Desktop/push/tabookey-gasless/server/../build/server/bin
go build -o /home/nervehammer/Desktop/push/tabookey-gasless/server/../build/server/bin/RelayHttpServer src/RelayHttpServer.go src/utils.go
strip /home/nervehammer/Desktop/push/tabookey-gasless/server/../build/server/bin/RelayHttpServer
make: Leaving directory '/home/nervehammer/Desktop/push/tabookey-gasless/server'
./restart-relay.sh: line 56: truffle: command not found
onexit
./restart-relay.sh: line 15:  1251 Terminated              sh -c "$GANACHE -d |grep ganache-core"

```

### PR DESCRIPTION
**Pull request by nervehammer**
fixes #162 and #163 

1. Installed `truffle` and `ganache-cli` as a global package for docker
2. Optimize dependencies installation for docker i.e. removed redundant `apt-get update` commands 
3. Updated `killdock.sh` script 
4. updated unstakeDelay value in `fundrelay` script.

### CODE REVIEW

File: restart-relay.sh [hunk 1]
```diff
@@ -37,7 +37,7 @@ blocktime=${T=0}
 pkill -f ganache-cli && echo killed old ganache.
 pkill -f RelayHttpServer && echo kill old relayserver
 
-GANACHE="$root/node_modules/.bin/ganache-cli -l 8000000 -b $blocktime -a 11 -h 0.0.0.0 "
+GANACHE="ganache-cli -l 8000000 -b $blocktime -a 11 -h 0.0.0.0 "
```
Comment (drortirosh) [inline restart-relay.sh]: use "`npx ganache-cli`, to use local ganache, global.

Comment (nervehammer) [reply restart-relay.sh]: yes i am changing it to `npx ganache-cli` and `npx truffle` as requested in the issue

**Comment by nervehammer** [comment]
@drortirosh made requested changes
